### PR TITLE
Made updates to site

### PR DESCRIPTION
**Pull request by matthewrsj**
* Home: changed date, took down time (until determined), took down thanks
* Schedule: cleared and changed to TBA
* Beginners: cleared and changed to TBA
* Advanced: cleared and changed to TBA
* Industry: cleared and changed to TBA

### CODE REVIEW

**Comment by matthewrsj** [comment]
@ramereth @Kennric can you please review?

**Comment by jordane** [comment]
@matthewrsj The About section also includes a description of last years advanced talks still.

**Comment by matthewrsj** [comment]
@jordane It also says that this is our first one. How about:

The OSL is kicking off DevOps BootCamp this year with the second annual DevOps DayCamp! DevOps DayCamp is a dual-track day with one track to help inexperienced attendees get started with DevOps, as well as a second track comprised of a hands-on hackathon with educational sessions throughout the day for the more advanced DevOps crowd. Advanced sessions will be given by industry professionals.

@ramereth @Kennric

**Comment by jordane** [comment]
@matthewrsj That sounds pretty good to me.

**Comment by matthewrsj** [comment]
Still needs beginner's track content, currently same as last year.

**Comment by ramereth** [comment]
@matthewrsj can you update the OSL section of the about page to include language about us being in CASS including a link to it?

**Pull request merged**
