### PR TITLE
Add CFP Button

### PR DESCRIPTION
**Pull request by matthewrsj**
CFP button with link to form added. 
Registration button added and commented out until registration link is ready.

### CODE REVIEW

**Comment by matthewrsj** [comment]
@ramereth @jordane @Phillels

**Comment by jordane** [comment]
+1

I do find the google form theme greatly amusing through. We have daycamp in the name, but a picture of a camp at night?

[daycamp picture](http://staff.osuosl.org/~jordane/daycamp.png)

**Comment by ramereth** [comment]
@matthewrsj Looks good although I'd like to see the button a little bigger. And the dark text in front of the dark-ish background of the button makes it a little hard to see. Maybe lighten up the text a little.

**Comment by matthewrsj** [comment]
@jordane @ramereth updated.

**Comment by ramereth** [comment]
:+1:

**Pull request merged**
